[project]
name = "cv-journey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Carlos Auquilla", email = "carlosauquillal@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "ultralytics>=8.4.166",
]

[project.scripts]
cv-journey = "cv_journey:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
